version: '3.8'

services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  app:
    build:
      context: .
      args:
        TARGET: ${TARGET:-all}
    env_file: .env
    depends_on:
      - redis
    ports:
      - "8000:8000"
      - "8501:8501"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    environment:
      - REDIS_URL=redis://redis:6379/0
    command: ${COMMAND:-}

volumes:
  redis_data: 